var annotated_dup =
[
    [ "cluster_mapping", "structcluster__mapping.html", "structcluster__mapping" ],
    [ "cmn600_cfgm_reg", "structcmn600__cfgm__reg.html", "structcmn600__cfgm__reg" ],
    [ "cmn600_ctx", "structcmn600__ctx.html", "structcmn600__ctx" ],
    [ "cmn600_cxg_ha_reg", "structcmn600__cxg__ha__reg.html", "structcmn600__cxg__ha__reg" ],
    [ "cmn600_cxg_ra_reg", "structcmn600__cxg__ra__reg.html", "structcmn600__cxg__ra__reg" ],
    [ "cmn600_cxla_reg", "structcmn600__cxla__reg.html", "structcmn600__cxla__reg" ],
    [ "cmn600_dn_reg", "structcmn600__dn__reg.html", "structcmn600__dn__reg" ],
    [ "cmn600_dt_reg", "structcmn600__dt__reg.html", "structcmn600__dt__reg" ],
    [ "cmn600_hnf_reg", "structcmn600__hnf__reg.html", "structcmn600__hnf__reg" ],
    [ "cmn600_hni_reg", "structcmn600__hni__reg.html", "structcmn600__hni__reg" ],
    [ "cmn600_mxp_reg", "structcmn600__mxp__reg.html", "structcmn600__mxp__reg" ],
    [ "cmn600_qos_reg", "structcmn600__qos__reg.html", "structcmn600__qos__reg" ],
    [ "cmn600_rnd_reg", "structcmn600__rnd__reg.html", "structcmn600__rnd__reg" ],
    [ "cmn600_rni_reg", "structcmn600__rni__reg.html", "structcmn600__rni__reg" ],
    [ "cmn600_rnsam_reg", "structcmn600__rnsam__reg.html", "structcmn600__rnsam__reg" ],
    [ "cmn600_sbsx_reg", "structcmn600__sbsx__reg.html", "structcmn600__sbsx__reg" ],
    [ "cxg_link_regs", "structcxg__link__regs.html", "structcxg__link__regs" ],
    [ "cxg_wait_condition_data", "structcxg__wait__condition__data.html", "structcxg__wait__condition__data" ],
    [ "external_rnsam_tuple", "structexternal__rnsam__tuple.html", "structexternal__rnsam__tuple" ],
    [ "mod_cmn600_ccix_config_api", "structmod__cmn600__ccix__config__api.html", "structmod__cmn600__ccix__config__api" ],
    [ "mod_cmn600_ccix_ha_mmap", "structmod__cmn600__ccix__ha__mmap.html", "structmod__cmn600__ccix__ha__mmap" ],
    [ "mod_cmn600_ccix_host_node_config", "structmod__cmn600__ccix__host__node__config.html", "structmod__cmn600__ccix__host__node__config" ],
    [ "mod_cmn600_ccix_remote_node_config", "structmod__cmn600__ccix__remote__node__config.html", "structmod__cmn600__ccix__remote__node__config" ],
    [ "mod_cmn600_config", "structmod__cmn600__config.html", "structmod__cmn600__config" ],
    [ "mod_cmn600_memory_region_map", "structmod__cmn600__memory__region__map.html", "structmod__cmn600__memory__region__map" ],
    [ "node_header", "structnode__header.html", "structnode__header" ]
];